#!/bin/sh

# FIRST RUN (Debian)

APT="/etc/apt/sources.list.d/ansible.list"

if [ ! -r $APT ];
then
	echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main" | sudo tee $APT && \
	printf "\e[32m-->\e[0m Adding Ansible repository" && \
	SUCCESS=YES
fi

if [ -r $APT ];
then
	sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
	sudo apt update
	sudo apt install ansible
fi
