#!/bin/sh

# Description : Ansible installer script
#
# Author : Jorge Barrientos Poisson
#
# ChangeLog : 
# 2021.11.08 | 1st quick draft. Debian only


# Debian Based
ANSIBLE_REPO_URL="deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main"
ANSIBLE_REPO_FILE="/etc/apt/sources.list.d/ansible.list"

ansible_addrepo() {
	if [ ! -r $ANSIBLE_REPO_FILE ];
	then
		echo $ANSIBLE_REPO_URL | sudo tee $ANSIBLE_REPO_FILE > /dev/null && \
		printf "\e[32m-->\e[0m Adding Ansible repository to %s" $ANSIBLE_REPO_FILE
	fi
}

ansible_install_debian() {
	if [ -r $ANSIBLE_REPO_FILE ];
	then
		sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
		sudo apt update
		sudo apt install ansible
	fi
}

ansible_addrepo && ansible_install_debian
