#!/bin/sh

# Description:
# Query the ClouDNS server to update my dynamic IP 
#
# Author:
# Jorge Barrientos Poisson
#
# ChangeLog:
# 2020.03.09 | Fixed a bug which downloaded the API webpage over and over.
# 2018.xx.xx | 1st version of this script

scriptname=$( basename $0 )

AREGISTER_LAGUNALABS="https://ipv4.cloudns.net/api/dynamicURL/?q=MTQxOTk2ODoyNDgyODg3NTo3M2E5NGNkNDRlODBiMWNhY2ZjYzFjYjQyODFmMWRlZGU5NzVlOGUyMmYzMWI2ZmJhMTA4ZTc5ZTNiNWU5MDQx"
AREGISTER_SEAFILE="https://ipv4.cloudns.net/api/dynamicURL/?q=MTQxOTk2ODoyNDgyODU1NDpkMDA3MTEzYjQ5MDVhMGMzNGI4OWQxNTcxOTVmNDA3MThiODRjODhjMjU2ZDU1YjNlYTIzZTAyZDI1ODRjNjE1"
AREGISTER_OFFSITE="https://ipv4.cloudns.net/api/dynamicURL/?q=MTQxOTk2ODoyNDgyODg3Njo1OTNiNzRkMTM2MWYxYzUyNGU2ZjRmYjQ4MWFjNjE1NmE5Y2Y0M2UzOGRhOTNkYmNiZGZhYWU3NTQxZWUzYTdm"

usage() {
	printf "usage: %s [-hs] <server>\n" $scriptname
	printf "   -h,     --help\t\tshow this help message\n"
	printf "   -s      --server\tnotify local IP of the given server to ClouDNS\n"
}

query() {
	if [ ! -z $1 ];
	then
		wget -q --read-timeout=0.0 --waitretry=5 --tries 400 --background "$1" -O - > /dev/null 2>&1
		exit 0
	else
		printf "ERROR: no server specified\n"
		exit 1
	fi
}

check_args() {
	if [ $# -eq 0 ];
	then
		# script is called with zero arguments 
		usage
		exit 0
	else
		# one or more arguments are used
		while [ "$1" ];
		do
			# list of accepted arguments
			case "$1" in

				# default help option
				"-h"|"--help")
					usage
					exit 0
					;;
				"-s"|"--server")
					case $2 in
						"lagunalabs")
							query "$AREGISTER_LAGUNALABS"
							;;
						"seafile")
							query "$AREGISTER_SEAFILE"
							;;
						"offsite")
							query "$AREGISTER_OFFSITE"
							;;
						*)
							printf "server %s not recognized\n" $2
							exit 1
							;;
					esac
					;;
				*)
					usage
					exit 1
					;;
			esac
			# removes the first item from the list of given arguments ('$@')
			shift
		done	
	fi
}

main() {
	check_args "$@"
}

# MAIN PROGRAM
main "$@"

